package ChatApp;


/**
* ChatApp/Interfaz.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Tuesday, January 19, 2021 5:08:52 PM COT
*/

public interface Interfaz extends InterfazOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interfaz
