package ChatApp;


/**
* ChatApp/InterfazOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL.idl
* Tuesday, January 19, 2021 5:08:52 PM COT
*/

public interface InterfazOperations 
{
  String connection (String userName);
  void newMessages (String roomName, String message);
  String getMessages (String roomName);
  String listUsers (String roomName);
  void disconnect (String userName, String roomName);
} // interface InterfazOperations
